require "jcp.options"
require "jcp.keymaps"
require "jcp.plugins"
require "jcp.colorscheme"
require "jcp.cmp"
require "jcp.lsp"
require "jcp.telescope"
require "jcp.treesitter"
require "jcp.autopairs"
require "jcp.comment"
require "jcp.nvim-tree"
require "jcp.bufferline"
require "jcp.lualine"
require "jcp.impatient"
require "jcp.indentline"
require "jcp.alpha"
require "jcp.whichkey"
require "jcp.autocommands"
require("jcp.gitsigns")
require("jcp.toggleterm")
