#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export EDITOR=nvim
export MANPAGER='less'
export MANWIDTH=999
export MANPATH=$MANPATH:"/usr/local/texlive/2023/texmf-dist/doc/man"
export INFOPATH=$INFOPATH:"/usr/local/texlive/2023/texmf-dist/doc/info"

# Task Warrior
export TASKRC="~/.config/task/taskrc"

export PATH="/usr/local/go/bin":$PATH
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/go/bin":$PATH
export PATH="$HOME/.pyenv/shims:${PATH}"

# OS Specific Exports
case "$(uname -s)" in
Darwin)
	# echo 'Mac OS X'
    export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
	export PATH="$PATH:/opt/homebrew/bin"
	export PATH="$PATH:$HOME/Library/Python/3.9/bin/"
    export PATH="$PATH:/Applications/WezTerm.app/Contents/MacOS"
    ;;

Linux)
	# echo 'Linux'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac

