#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000

export EDITOR=nvim
export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Task Warrior
export TASKRC="~/.config/task/taskrc"

export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.pyenv/shims:${PATH}"
export PATH="$HOME/.local/share/neovim/bin":$PATH
export PATH="/usr/local/texlive/2023/bin/x86_64-linux":$PATH
export PATH="/usr/local/Cellar/libfaketime/0.9.10/bin":$PATH

export MANPATH=$MANPATH:"/usr/local/texlive/2023/texmf-dist/doc/man"
export INFOPATH=$INFOPATH:"/usr/local/texlive/2023/texmf-dist/doc/info"

# Make those MacOS Specific?
openssl_version="3"
export PATH="/usr/local/opt/openssl@${openssl_version}/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/openssl@${openssl_version}/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@${openssl_version}/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@${openssl_version}/lib/pkgconfig"

# OS Specific Exports
case "$(uname -s)" in
Darwin)
	# echo 'Mac OS X'
    export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
	;;

Linux)
	# echo 'Linux'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac

